### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by TruongHung02** [robsontenorio/laravel-keycloak-guard#119]
when i logout keycloak, old token still work on api guard. Is there any solution to this ?

**Comment by lauritzh** [comment]
Hey! Jumping in because I stumbled over this issue.

This is kind of how JWTs as `access_token` work. The guard can validate them "offline" without needing to contact your Keycloak, because they are inherently valid (and have a defined lifetime represented by the `iat` and `exp` claims). At the same time, this means the guard is not aware of a logout at the Keycloak instance.

Using the current implementation, you could mitigate this by using very short-living `access_token`. Something like a minute or so:      
![image](https://github.com/user-attachments/assets/03e6dc03-e9c4-4aac-844c-12516e85b7ba)

This way, the api guard would only accept tokens that were issued before the logout for at max 1 minute.

Alternatively, you could extend the guard to support the [OAuth 2.0 Token Introspection] mechanism: https://datatracker.ietf.org/doc/html/rfc7662        

For our current project, we went with the "use very short-living tokens" approach.

**Comment by jhoanborges** [comment]
+1
