### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by titoff002** [robsontenorio/laravel-keycloak-guard#3]
Hello,

I am testing your laravel module for keycloak.

I followed the instructions mentioned in the readme. But I have error messages that appear :

![image](https://user-images.githubusercontent.com/24948237/45293258-ebc0c100-b4f7-11e8-8e0f-73efe5db908d.png)

In your module, should we set the keycloack database: ie, should we tell your module that it must connect to the keycloak database? If yes, how ?

Can you help me ?

Regards,
Christophe

**Comment by robsontenorio** [comment]
Hi,

This also closes #4 .

About error, this is generic Laravel issue about routes configuration, not about package itself.

Maybe i should update docs, but:
- This package does not lookup for nothing outside the local project itself. 
- It does not interact with keycloak server or keyloack databases
- **It just validate if JWT token received by backend is valid , once we know de PUBLIC KEY of Keycloak Server**

And as a plus,
- Additionally it verifies if your local user is valid, because JWT token carries info about user

My project "users" table is something like this. 

ID | username | created_at | updated_at
--- | --------------| -------------- | ---------------
1 | johndoe | 2018-01-01 | 2018-01-01
2 | marygold | 2018-01-01 | 2018-01-01

The only reason "users" table exists is to keep the project consistent, because many business rules depends on it.

Fullname, email and other field are present in JWT token. It depends how your keycloak server is configured.
