### ISSUE TITLE
Acting as during tests

### ISSUE THREAD

**Issue by Ashk2a** [robsontenorio/laravel-keycloak-guard#96]
Hello,

I was using Laravel Passport before, the package proposes something like `Passport::actingAs` to simplify the generation of a token and authentication during tests. 

I haven't found an equivalent, but I'd like to know if there's a simple way to get the same behavior ?

**Comment by robsontenorio** [comment]
@Ashk2a  We don't have equivalent. I will accept a MR for this.

**Comment by Ashk2a** [comment]
@robsontenorio I'll try to do something like thast
@lotyp Yes you can do that (and set key env variable as empty) but you can't retrieve information

**Comment by Ashk2a** [comment]
I close the ticket, for the moment we can use `actingAs`

**Comment by tuytoosh** [comment]
I do not have a user table in reality because all information related to users is being handled in Keycloak. In order to pass the middleware, I have created a redundant `user` table to be able to use `actingAs()`, which seems pretty odd. I think it would be better to have a mechanism to pass authentication without requiring the creation of a user. Something like this: `$this->actingWithKeycloakToken()`.

I will try to delve into the Laravel source code and this package as well to find out how to accomplish this.
